interactions:
- request:
    body: !!binary |
      eyJoZWFkZXJzIjogeyJSZWZlcmVyIjogImh0dHA6Ly9sb2NhbGhvc3Q6ODkwMS9hcGkvdG9rZW4t
      YXV0aC8iLCAiQ29udGVudC1UeXBlIjogImFwcGxpY2F0aW9uL2pzb247IGNoYXJzZXQ9VVRGLTgi
      fSwgIm5leHQiOiAiaHR0cDovL2xvY2FsaG9zdDo4OTAxL2FwaS8iLCAidXNlcm5hbWUiOiAib3Nt
      YXh4aSIsICJwYXNzd29yZCI6ICJ3cm9uZy1wYXNzd29yZCJ9
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      Content-Length: ['207']
      Content-Type: [application/json]
      User-Agent: [python-requests/2.6.2 CPython/3.4.2 Linux/3.16.0-4-amd64]
    method: POST
    uri: http://localhost:8901/api/token-auth/
  response:
    body: {string: '{"non_field_errors":["Unable to login with provided credentials."]}'}
    headers:
      Allow: ['POST, OPTIONS']
      Connection: [close]
      Content-Type: [application/json]
      Date: ['Tue, 17 Nov 2015 11:35:08 GMT']
      Server: [Werkzeug/0.10.4 Python/3.4.3]
      Vary: [Accept]
      X-Frame-Options: [SAMEORIGIN]
    status: {code: 400, message: BAD REQUEST}
version: 1
